import { categorias } from "./Categorias";
import { bodegas } from "./Bodegas";

const productos = [
  {
    idProducto: 1,
    nombre: "Jeans Hombre",
    referencia: "JEANS-HOM-001",
    serial: "SN001234567",
    estado: "NACIONALIZADO",
    peso: 0.4,
    cantidad: 150,
    cantidad_nacionalizado: 120,
    cantidad_no_nacionalizado: 30,
    observacion: "Jeans para hombre, talla 32, color azul",
    UNIDAD_DE_CARGA_idUnidad: 1,
    BODEGA_idBodega: 1,
    CATEGORIA_idCategoria: 2,
    categoria: categorias.find(c => c.idCategoria === 2),
    bodega: bodegas.find(b => b.idBodega === 1)
  },
  {
    idProducto: 2,
    nombre: "Smartphone Samsung Galaxy",
    referencia: "SAMS-GAL-002",
    serial: "SN002345678",
    estado: "NO NACIONALIZADO",
    peso: 0.2,
    cantidad: 75,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 75,
    observacion: "Smartphone de 6.1 pulgadas, 128GB",
    UNIDAD_DE_CARGA_idUnidad: 1,
    BODEGA_idBodega: 1,
    CATEGORIA_idCategoria: 1,
    categoria: categorias.find(c => c.idCategoria === 1),
    bodega: bodegas.find(b => b.idBodega === 1)
  },
  {
    idProducto: 3,
    nombre: "Camiseta de Algodón",
    referencia: "TEXT-CAM-003",
    serial: "SN003456789",
    estado: "NACIONALIZADO",
    peso: 0.15,
    cantidad: 200,
    cantidad_nacionalizado: 200,
    cantidad_no_nacionalizado: 0,
    observacion: "Camiseta 100% algodón, talla M",
    UNIDAD_DE_CARGA_idUnidad: 2,
    BODEGA_idBodega: 2,
    CATEGORIA_idCategoria: 2,
    categoria: categorias.find(c => c.idCategoria === 2),
    bodega: bodegas.find(b => b.idBodega === 2)
  },
  {
    idProducto: 4,
    nombre: "Pantalón Jeans",
    referencia: "TEXT-JEA-004",
    serial: "SN004567890",
    estado: "NO NACIONALIZADO",
    peso: 0.4,
    cantidad: 80,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 80,
    observacion: "Pantalón jeans azul, talla 32",
    UNIDAD_DE_CARGA_idUnidad: 2,
    BODEGA_idBodega: 2,
    CATEGORIA_idCategoria: 2,
    categoria: categorias.find(c => c.idCategoria === 2),
    bodega: bodegas.find(b => b.idBodega === 2)
  },
  {
    idProducto: 5,
    nombre: "Café Colombiano",
    referencia: "ALIM-CAF-005",
    serial: "SN005678901",
    estado: "NACIONALIZADO",
    peso: 0.5,
    cantidad: 300,
    cantidad_nacionalizado: 300,
    cantidad_no_nacionalizado: 0,
    observacion: "Café colombiano premium, 500g",
    UNIDAD_DE_CARGA_idUnidad: 3,
    BODEGA_idBodega: 6,
    CATEGORIA_idCategoria: 3,
    categoria: categorias.find(c => c.idCategoria === 3),
    bodega: bodegas.find(b => b.idBodega === 6)
  },
  {
    idProducto: 6,
    nombre: "Chocolate Artesanal",
    referencia: "ALIM-CHO-006",
    serial: "SN006789012",
    estado: "NO NACIONALIZADO",
    peso: 0.1,
    cantidad: 120,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 120,
    observacion: "Chocolate artesanal 70% cacao",
    UNIDAD_DE_CARGA_idUnidad: 3,
    BODEGA_idBodega: 6,
    CATEGORIA_idCategoria: 3,
    categoria: categorias.find(c => c.idCategoria === 3),
    bodega: bodegas.find(b => b.idBodega === 6)
  },
  {
    idProducto: 7,
    nombre: "Taladro Eléctrico",
    referencia: "HERR-TAL-007",
    serial: "SN007890123",
    estado: "NACIONALIZADO",
    peso: 2.0,
    cantidad: 45,
    cantidad_nacionalizado: 45,
    cantidad_no_nacionalizado: 0,
    observacion: "Taladro eléctrico 20V, con batería",
    UNIDAD_DE_CARGA_idUnidad: 4,
    BODEGA_idBodega: 4,
    CATEGORIA_idCategoria: 4,
    categoria: categorias.find(c => c.idCategoria === 4),
    bodega: bodegas.find(b => b.idBodega === 4)
  },
  {
    idProducto: 8,
    nombre: "Destornillador Phillips",
    referencia: "HERR-DES-008",
    serial: "SN008901234",
    estado: "NO NACIONALIZADO",
    peso: 0.3,
    cantidad: 60,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 60,
    observacion: "Destornillador Phillips #2, mango ergonómico",
    UNIDAD_DE_CARGA_idUnidad: 4,
    BODEGA_idBodega: 4,
    CATEGORIA_idCategoria: 4,
    categoria: categorias.find(c => c.idCategoria === 4),
    bodega: bodegas.find(b => b.idBodega === 4)
  },
  {
    idProducto: 9,
    nombre: "Filtro de Aceite",
    referencia: "AUTO-FIL-009",
    serial: "SN009012345",
    estado: "NACIONALIZADO",
    peso: 0.2,
    cantidad: 90,
    cantidad_nacionalizado: 90,
    cantidad_no_nacionalizado: 0,
    observacion: "Filtro de aceite para motor 2.0L",
    UNIDAD_DE_CARGA_idUnidad: 5,
    BODEGA_idBodega: 5,
    CATEGORIA_idCategoria: 5,
    categoria: categorias.find(c => c.idCategoria === 5),
    bodega: bodegas.find(b => b.idBodega === 5)
  },
  {
    idProducto: 10,
    nombre: "Pastillas de Freno",
    referencia: "AUTO-PAS-010",
    serial: "SN010123456",
    estado: "NO NACIONALIZADO",
    peso: 0.5,
    cantidad: 40,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 40,
    observacion: "Pastillas de freno cerámicas, juego completo",
    UNIDAD_DE_CARGA_idUnidad: 5,
    BODEGA_idBodega: 5,
    CATEGORIA_idCategoria: 5,
    categoria: categorias.find(c => c.idCategoria === 5),
    bodega: bodegas.find(b => b.idBodega === 5)
  },
  {
    idProducto: 11,
    nombre: "Peluche Grande",
    referencia: "JUEG-PEL-011",
    serial: "SN011234567",
    estado: "NACIONALIZADO",
    peso: 0.8,
    cantidad: 25,
    cantidad_nacionalizado: 25,
    cantidad_no_nacionalizado: 0,
    observacion: "Peluche de oso grande, 50cm",
    UNIDAD_DE_CARGA_idUnidad: 6,
    BODEGA_idBodega: 3,
    CATEGORIA_idCategoria: 6,
    categoria: categorias.find(c => c.idCategoria === 6),
    bodega: bodegas.find(b => b.idBodega === 3)
  },
  {
    idProducto: 12,
    nombre: "Juego de Mesa",
    referencia: "JUEG-MES-012",
    serial: "SN012345678",
    estado: "NO NACIONALIZADO",
    peso: 1.2,
    cantidad: 15,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 15,
    observacion: "Juego de mesa familiar, 2-6 jugadores",
    UNIDAD_DE_CARGA_idUnidad: 6,
    BODEGA_idBodega: 3,
    CATEGORIA_idCategoria: 6,
    categoria: categorias.find(c => c.idCategoria === 6),
    bodega: bodegas.find(b => b.idBodega === 3)
  },
  {
    idProducto: 13,
    nombre: "Lámpara de Mesa",
    referencia: "HOG-LAM-013",
    serial: "SN013456789",
    estado: "NACIONALIZADO",
    peso: 1.5,
    cantidad: 35,
    cantidad_nacionalizado: 35,
    cantidad_no_nacionalizado: 0,
    observacion: "Lámpara de mesa LED, luz ajustable",
    UNIDAD_DE_CARGA_idUnidad: 7,
    BODEGA_idBodega: 7,
    CATEGORIA_idCategoria: 7,
    categoria: categorias.find(c => c.idCategoria === 7),
    bodega: bodegas.find(b => b.idBodega === 7)
  },
  {
    idProducto: 14,
    nombre: "Sartén Antiadherente",
    referencia: "HOG-SAR-014",
    serial: "SN014567890",
    estado: "NO NACIONALIZADO",
    peso: 0.8,
    cantidad: 50,
    cantidad_nacionalizado: 0,
    cantidad_no_nacionalizado: 50,
    observacion: "Sartén antiadherente 24cm, mango ergonómico",
    UNIDAD_DE_CARGA_idUnidad: 7,
    BODEGA_idBodega: 7,
    CATEGORIA_idCategoria: 7,
    categoria: categorias.find(c => c.idCategoria === 7),
    bodega: bodegas.find(b => b.idBodega === 7)
  },
  {
    idProducto: 15,
    nombre: "Balón de Fútbol",
    referencia: "DEP-BAL-015",
    serial: "SN015678901",
    estado: "DISPONIBLE",
    peso: 0.4,
    cantidad: 30,
    cantidad_nacionalizado: 20,
    cantidad_no_nacionalizado: 10,
    observacion: "Balón de fútbol profesional, talla 5",
    UNIDAD_DE_CARGA_idUnidad: 8,
    BODEGA_idBodega: 2,
    CATEGORIA_idCategoria: 8,
    categoria: categorias.find(c => c.idCategoria === 8),
    bodega: bodegas.find(b => b.idBodega === 2)
  },
  {
    idProducto: 16,
    nombre: "Raqueta de Tenis",
    referencia: "DEP-RAQ-016",
    serial: "SN016789012",
    estado: "DISPONIBLE",
    peso: 0.3,
    cantidad: 20,
    cantidad_nacionalizado: 15,
    cantidad_no_nacionalizado: 5,
    observacion: "Raqueta de tenis profesional, encordada",
    UNIDAD_DE_CARGA_idUnidad: 8,
    BODEGA_idBodega: 2,
    CATEGORIA_idCategoria: 8,
    categoria: categorias.find(c => c.idCategoria === 8),
    bodega: bodegas.find(b => b.idBodega === 2)
  },
  {
    idProducto: 17,
    nombre: "Tablet iPad",
    referencia: "ELE-TAB-017",
    serial: "SN017890123",
    estado: "DISPONIBLE",
    peso: 0.5,
    cantidad: 55,
    cantidad_nacionalizado: 40,
    cantidad_no_nacionalizado: 15,
    observacion: "Tablet iPad 10.2 pulgadas, 64GB",
    UNIDAD_DE_CARGA_idUnidad: 9,
    BODEGA_idBodega: 1,
    CATEGORIA_idCategoria: 1,
    categoria: categorias.find(c => c.idCategoria === 1),
    bodega: bodegas.find(b => b.idBodega === 1)
  },
  {
    idProducto: 18,
    nombre: "Auriculares Bluetooth",
    referencia: "ELE-AUR-018",
    serial: "SN018901234",
    estado: "DISPONIBLE",
    peso: 0.2,
    cantidad: 100,
    cantidad_nacionalizado: 70,
    cantidad_no_nacionalizado: 30,
    observacion: "Auriculares Bluetooth con cancelación de ruido",
    UNIDAD_DE_CARGA_idUnidad: 9,
    BODEGA_idBodega: 1,
    CATEGORIA_idCategoria: 1,
    categoria: categorias.find(c => c.idCategoria === 1),
    bodega: bodegas.find(b => b.idBodega === 1)
  }
];

export { productos };
