import { productos } from "../producto/Productos";
import { guiasCarga } from "../guiaCarga/GuiasCarga";
import { unidadesCarga } from "../guiaCarga/UnidadesCarga";
import { bodegas } from "../producto/Bodegas";
import { customers } from "../customer/Customers";

const existencias = [
  // Jeans Hombre - Unidad individual con serial específico
  {
    idExistencia: 1,
    estado: "NACIONALIZADO",
    serial: "JEANS-001-2024-001",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 1,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-001",
    producto: productos.find(p => p.idProducto === 1),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 2,
    estado: "NACIONALIZADO",
    serial: "JEANS-001-2024-002",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 1,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-001",
    producto: productos.find(p => p.idProducto === 1),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 3,
    estado: "NO_NACIONALIZADO",
    serial: "JEANS-001-2024-003",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 1,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-001",
    producto: productos.find(p => p.idProducto === 1),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  // Smartphone Samsung Galaxy - Unidades individuales
  {
    idExistencia: 4,
    estado: "NO_NACIONALIZADO",
    serial: "SAMS-GAL-002-001",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 2,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-002",
    producto: productos.find(p => p.idProducto === 2),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 5,
    estado: "NO_NACIONALIZADO",
    serial: "SAMS-GAL-002-002",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 2,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-002",
    producto: productos.find(p => p.idProducto === 2),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  // Camiseta de Algodón - Unidades individuales
  {
    idExistencia: 6,
    estado: "NACIONALIZADO",
    serial: "TEXT-CAM-003-001",
    GUIA_DE_CARGA_idGuia: 2,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 3,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-003",
    producto: productos.find(p => p.idProducto === 3),
    guiaCarga: guiasCarga.find(g => g.idGuia === 2),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 2)
  },
  {
    idExistencia: 7,
    estado: "NACIONALIZADO",
    serial: "TEXT-CAM-003-002",
    GUIA_DE_CARGA_idGuia: 2,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 3,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-003",
    producto: productos.find(p => p.idProducto === 3),
    guiaCarga: guiasCarga.find(g => g.idGuia === 2),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 2)
  },
  // Pantalón Jeans - Unidades individuales
  {
    idExistencia: 8,
    estado: "NO_NACIONALIZADO",
    serial: "TEXT-JEA-004-001",
    GUIA_DE_CARGA_idGuia: 2,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 4,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-004",
    producto: productos.find(p => p.idProducto === 4),
    guiaCarga: guiasCarga.find(g => g.idGuia === 2),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 2)
  },
  {
    idExistencia: 9,
    estado: "NO_NACIONALIZADO",
    serial: "TEXT-JEA-004-002",
    GUIA_DE_CARGA_idGuia: 2,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 4,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-004",
    producto: productos.find(p => p.idProducto === 4),
    guiaCarga: guiasCarga.find(g => g.idGuia === 2),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 2)
  },
  // Café Colombiano - Unidades individuales
  {
    idExistencia: 10,
    estado: "NACIONALIZADO",
    serial: "ALIM-CAF-005-001",
    GUIA_DE_CARGA_idGuia: 3,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 5,
    PRODUCTO_BODEGA_idBodega: 6,
    UNIDAD_DE_CARGA_idUnidad: "UC-005",
    producto: productos.find(p => p.idProducto === 5),
    guiaCarga: guiasCarga.find(g => g.idGuia === 3),
    bodega: bodegas.find(b => b.idBodega === 6),
    cliente: customers.find(c => c.idCliente === 3)
  },
  {
    idExistencia: 11,
    estado: "NACIONALIZADO",
    serial: "ALIM-CAF-005-002",
    GUIA_DE_CARGA_idGuia: 3,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 5,
    PRODUCTO_BODEGA_idBodega: 6,
    UNIDAD_DE_CARGA_idUnidad: "UC-005",
    producto: productos.find(p => p.idProducto === 5),
    guiaCarga: guiasCarga.find(g => g.idGuia === 3),
    bodega: bodegas.find(b => b.idBodega === 6),
    cliente: customers.find(c => c.idCliente === 3)
  },
  // Chocolate Artesanal - Unidades individuales
  {
    idExistencia: 12,
    estado: "NO_NACIONALIZADO",
    serial: "ALIM-CHO-006-001",
    GUIA_DE_CARGA_idGuia: 3,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 6,
    PRODUCTO_BODEGA_idBodega: 6,
    UNIDAD_DE_CARGA_idUnidad: "UC-006",
    producto: productos.find(p => p.idProducto === 6),
    guiaCarga: guiasCarga.find(g => g.idGuia === 3),
    bodega: bodegas.find(b => b.idBodega === 6),
    cliente: customers.find(c => c.idCliente === 3)
  },
  {
    idExistencia: 13,
    estado: "NO_NACIONALIZADO",
    serial: "ALIM-CHO-006-002",
    GUIA_DE_CARGA_idGuia: 3,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 6,
    PRODUCTO_BODEGA_idBodega: 6,
    UNIDAD_DE_CARGA_idUnidad: "UC-006",
    producto: productos.find(p => p.idProducto === 6),
    guiaCarga: guiasCarga.find(g => g.idGuia === 3),
    bodega: bodegas.find(b => b.idBodega === 6),
    cliente: customers.find(c => c.idCliente === 3)
  },
  // Taladro Eléctrico - Unidades individuales
  {
    idExistencia: 14,
    estado: "NACIONALIZADO",
    serial: "HERR-TAL-007-001",
    GUIA_DE_CARGA_idGuia: 4,
    GUIA_DE_CARGA_CLIENTE_idCliente: 4,
    PRODUCTO_idProducto: 7,
    PRODUCTO_BODEGA_idBodega: 4,
    producto: productos.find(p => p.idProducto === 7),
    guiaCarga: guiasCarga.find(g => g.idGuia === 4),
    bodega: bodegas.find(b => b.idBodega === 4),
    cliente: customers.find(c => c.idCliente === 4)
  },
  {
    idExistencia: 15,
    estado: "NACIONALIZADO",
    serial: "HERR-TAL-007-002",
    GUIA_DE_CARGA_idGuia: 4,
    GUIA_DE_CARGA_CLIENTE_idCliente: 4,
    PRODUCTO_idProducto: 7,
    PRODUCTO_BODEGA_idBodega: 4,
    UNIDAD_DE_CARGA_idUnidad: "UC-007",
    producto: productos.find(p => p.idProducto === 7),
    guiaCarga: guiasCarga.find(g => g.idGuia === 4),
    bodega: bodegas.find(b => b.idBodega === 4),
    cliente: customers.find(c => c.idCliente === 4)
  },
  // Destornillador Phillips - Unidades individuales
  {
    idExistencia: 16,
    estado: "NO_NACIONALIZADO",
    serial: "HERR-DES-008-001",
    GUIA_DE_CARGA_idGuia: 4,
    GUIA_DE_CARGA_CLIENTE_idCliente: 4,
    PRODUCTO_idProducto: 8,
    PRODUCTO_BODEGA_idBodega: 4,
    UNIDAD_DE_CARGA_idUnidad: "UC-008",
    producto: productos.find(p => p.idProducto === 8),
    guiaCarga: guiasCarga.find(g => g.idGuia === 4),
    bodega: bodegas.find(b => b.idBodega === 4),
    cliente: customers.find(c => c.idCliente === 4)
  },
  {
    idExistencia: 17,
    estado: "NO_NACIONALIZADO",
    serial: "HERR-DES-008-002",
    GUIA_DE_CARGA_idGuia: 4,
    GUIA_DE_CARGA_CLIENTE_idCliente: 4,
    PRODUCTO_idProducto: 8,
    PRODUCTO_BODEGA_idBodega: 4,
    UNIDAD_DE_CARGA_idUnidad: "UC-008",
    producto: productos.find(p => p.idProducto === 8),
    guiaCarga: guiasCarga.find(g => g.idGuia === 4),
    bodega: bodegas.find(b => b.idBodega === 4),
    cliente: customers.find(c => c.idCliente === 4)
  },
  // Filtro de Aceite - Unidades individuales
  {
    idExistencia: 18,
    estado: "NACIONALIZADO",
    serial: "AUTO-FIL-009-001",
    GUIA_DE_CARGA_idGuia: 5,
    GUIA_DE_CARGA_CLIENTE_idCliente: 5,
    PRODUCTO_idProducto: 9,
    PRODUCTO_BODEGA_idBodega: 5,
    UNIDAD_DE_CARGA_idUnidad: "UC-009",
    producto: productos.find(p => p.idProducto === 9),
    guiaCarga: guiasCarga.find(g => g.idGuia === 5),
    bodega: bodegas.find(b => b.idBodega === 5),
    cliente: customers.find(c => c.idCliente === 5)
  },
  {
    idExistencia: 19,
    estado: "NACIONALIZADO",
    serial: "AUTO-FIL-009-002",
    GUIA_DE_CARGA_idGuia: 5,
    GUIA_DE_CARGA_CLIENTE_idCliente: 5,
    PRODUCTO_idProducto: 9,
    PRODUCTO_BODEGA_idBodega: 5,
    UNIDAD_DE_CARGA_idUnidad: "UC-009",
    producto: productos.find(p => p.idProducto === 9),
    guiaCarga: guiasCarga.find(g => g.idGuia === 5),
    bodega: bodegas.find(b => b.idBodega === 5),
    cliente: customers.find(c => c.idCliente === 5)
  },
  // Pastillas de Freno - Unidades individuales
  {
    idExistencia: 20,
    estado: "NO_NACIONALIZADO",
    serial: "AUTO-PAS-010-001",
    GUIA_DE_CARGA_idGuia: 5,
    GUIA_DE_CARGA_CLIENTE_idCliente: 5,
    PRODUCTO_idProducto: 10,
    PRODUCTO_BODEGA_idBodega: 5,
    UNIDAD_DE_CARGA_idUnidad: "UC-010",
    producto: productos.find(p => p.idProducto === 10),
    guiaCarga: guiasCarga.find(g => g.idGuia === 5),
    bodega: bodegas.find(b => b.idBodega === 5),
    cliente: customers.find(c => c.idCliente === 5)
  },
  {
    idExistencia: 21,
    estado: "NO_NACIONALIZADO",
    serial: "AUTO-PAS-010-002",
    GUIA_DE_CARGA_idGuia: 5,
    GUIA_DE_CARGA_CLIENTE_idCliente: 5,
    PRODUCTO_idProducto: 10,
    PRODUCTO_BODEGA_idBodega: 5,
    UNIDAD_DE_CARGA_idUnidad: "UC-010",
    producto: productos.find(p => p.idProducto === 10),
    guiaCarga: guiasCarga.find(g => g.idGuia === 5),
    bodega: bodegas.find(b => b.idBodega === 5),
    cliente: customers.find(c => c.idCliente === 5)
  },
  // Peluche Grande - Unidades individuales
  {
    idExistencia: 22,
    estado: "NACIONALIZADO",
    serial: "JUEG-PEL-011-001",
    GUIA_DE_CARGA_idGuia: 6,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 11,
    PRODUCTO_BODEGA_idBodega: 3,
    UNIDAD_DE_CARGA_idUnidad: "UC-011",
    producto: productos.find(p => p.idProducto === 11),
    guiaCarga: guiasCarga.find(g => g.idGuia === 6),
    bodega: bodegas.find(b => b.idBodega === 3),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 23,
    estado: "NACIONALIZADO",
    serial: "JUEG-PEL-011-002",
    GUIA_DE_CARGA_idGuia: 6,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 11,
    PRODUCTO_BODEGA_idBodega: 3,
    UNIDAD_DE_CARGA_idUnidad: "UC-011",
    producto: productos.find(p => p.idProducto === 11),
    guiaCarga: guiasCarga.find(g => g.idGuia === 6),
    bodega: bodegas.find(b => b.idBodega === 3),
    cliente: customers.find(c => c.idCliente === 1)
  },
  // Juego de Mesa - Unidades individuales
  {
    idExistencia: 24,
    estado: "NO_NACIONALIZADO",
    serial: "JUEG-MES-012-001",
    GUIA_DE_CARGA_idGuia: 6,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 12,
    PRODUCTO_BODEGA_idBodega: 3,
    UNIDAD_DE_CARGA_idUnidad: "UC-012",
    producto: productos.find(p => p.idProducto === 12),
    guiaCarga: guiasCarga.find(g => g.idGuia === 6),
    bodega: bodegas.find(b => b.idBodega === 3),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 25,
    estado: "NO_NACIONALIZADO",
    serial: "JUEG-MES-012-002",
    GUIA_DE_CARGA_idGuia: 6,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 12,
    PRODUCTO_BODEGA_idBodega: 3,
    UNIDAD_DE_CARGA_idUnidad: "UC-012",
    producto: productos.find(p => p.idProducto === 12),
    guiaCarga: guiasCarga.find(g => g.idGuia === 6),
    bodega: bodegas.find(b => b.idBodega === 3),
    cliente: customers.find(c => c.idCliente === 1)
  },
  // Lámpara de Mesa - Unidades individuales
  {
    idExistencia: 26,
    estado: "NACIONALIZADO",
    serial: "HOG-LAM-013-001",
    GUIA_DE_CARGA_idGuia: 7,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 13,
    PRODUCTO_BODEGA_idBodega: 7,
    UNIDAD_DE_CARGA_idUnidad: "UC-013",
    producto: productos.find(p => p.idProducto === 13),
    guiaCarga: guiasCarga.find(g => g.idGuia === 7),
    bodega: bodegas.find(b => b.idBodega === 7),
    cliente: customers.find(c => c.idCliente === 2)
  },
  {
    idExistencia: 27,
    estado: "NACIONALIZADO",
    serial: "HOG-LAM-013-002",
    GUIA_DE_CARGA_idGuia: 7,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 13,
    PRODUCTO_BODEGA_idBodega: 7,
    UNIDAD_DE_CARGA_idUnidad: "UC-013",
    producto: productos.find(p => p.idProducto === 13),
    guiaCarga: guiasCarga.find(g => g.idGuia === 7),
    bodega: bodegas.find(b => b.idBodega === 7),
    cliente: customers.find(c => c.idCliente === 2)
  },
  // Sartén Antiadherente - Unidades individuales
  {
    idExistencia: 28,
    estado: "NO_NACIONALIZADO",
    serial: "HOG-SAR-014-001",
    GUIA_DE_CARGA_idGuia: 7,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 14,
    PRODUCTO_BODEGA_idBodega: 7,
    UNIDAD_DE_CARGA_idUnidad: "UC-013",
    producto: productos.find(p => p.idProducto === 14),
    guiaCarga: guiasCarga.find(g => g.idGuia === 7),
    bodega: bodegas.find(b => b.idBodega === 7),
    cliente: customers.find(c => c.idCliente === 2)
  },
  {
    idExistencia: 29,
    estado: "NO_NACIONALIZADO",
    serial: "HOG-SAR-014-002",
    GUIA_DE_CARGA_idGuia: 7,
    GUIA_DE_CARGA_CLIENTE_idCliente: 2,
    PRODUCTO_idProducto: 14,
    PRODUCTO_BODEGA_idBodega: 7,
    UNIDAD_DE_CARGA_idUnidad: "UC-013",
    producto: productos.find(p => p.idProducto === 14),
    guiaCarga: guiasCarga.find(g => g.idGuia === 7),
    bodega: bodegas.find(b => b.idBodega === 7),
    cliente: customers.find(c => c.idCliente === 2)
  },
  // Balón de Fútbol - Unidades individuales
  {
    idExistencia: 30,
    estado: "NACIONALIZADO",
    serial: "DEP-BAL-015-001",
    GUIA_DE_CARGA_idGuia: 8,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 15,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-014",
    producto: productos.find(p => p.idProducto === 15),
    guiaCarga: guiasCarga.find(g => g.idGuia === 8),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 3)
  },
  {
    idExistencia: 31,
    estado: "NO_NACIONALIZADO",
    serial: "DEP-BAL-015-002",
    GUIA_DE_CARGA_idGuia: 8,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 15,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-014",
    producto: productos.find(p => p.idProducto === 15),
    guiaCarga: guiasCarga.find(g => g.idGuia === 8),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 3)
  },
  // Raqueta de Tenis - Unidades individuales
  {
    idExistencia: 32,
    estado: "NACIONALIZADO",
    serial: "DEP-RAQ-016-001",
    GUIA_DE_CARGA_idGuia: 8,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 16,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-014",
    producto: productos.find(p => p.idProducto === 16),
    guiaCarga: guiasCarga.find(g => g.idGuia === 8),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 3)
  },
  {
    idExistencia: 33,
    estado: "NO_NACIONALIZADO",
    serial: "DEP-RAQ-016-002",
    GUIA_DE_CARGA_idGuia: 8,
    GUIA_DE_CARGA_CLIENTE_idCliente: 3,
    PRODUCTO_idProducto: 16,
    PRODUCTO_BODEGA_idBodega: 2,
    UNIDAD_DE_CARGA_idUnidad: "UC-014",
    producto: productos.find(p => p.idProducto === 16),
    guiaCarga: guiasCarga.find(g => g.idGuia === 8),
    bodega: bodegas.find(b => b.idBodega === 2),
    cliente: customers.find(c => c.idCliente === 3)
  },
  // Tablet iPad - Unidades individuales
  {
    idExistencia: 34,
    estado: "NACIONALIZADO",
    serial: "ELE-TAB-017-001",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 17,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-001",
    producto: productos.find(p => p.idProducto === 17),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 35,
    estado: "NO_NACIONALIZADO",
    serial: "ELE-TAB-017-002",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 17,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-001",
    producto: productos.find(p => p.idProducto === 17),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  // Auriculares Bluetooth - Unidades individuales
  {
    idExistencia: 36,
    estado: "NACIONALIZADO",
    serial: "ELE-AUR-018-001",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 18,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-002",
    producto: productos.find(p => p.idProducto === 18),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  },
  {
    idExistencia: 37,
    estado: "NO_NACIONALIZADO",
    serial: "ELE-AUR-018-002",
    GUIA_DE_CARGA_idGuia: 1,
    GUIA_DE_CARGA_CLIENTE_idCliente: 1,
    PRODUCTO_idProducto: 18,
    PRODUCTO_BODEGA_idBodega: 1,
    UNIDAD_DE_CARGA_idUnidad: "UC-002",
    producto: productos.find(p => p.idProducto === 18),
    guiaCarga: guiasCarga.find(g => g.idGuia === 1),
    bodega: bodegas.find(b => b.idBodega === 1),
    cliente: customers.find(c => c.idCliente === 1)
  }
];

export { existencias };
